name = "template"
compatibility_date = "2024-04-19"


[durable_objects]
bindings = [
  {name = "SESSION", class_name = "WebMultiViewSession"}
]

[[r2_buckets]]
binding = "IMAGES" 
bucket_name = "images" 
preview_bucket_name = "images" 

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["WebMultiViewSession"]