name = "template"
compatibility_date = "2024-04-19"


[durable_objects]
bindings = [
  {name = "SYNC", class_name = "WebMultiViewSync"},
  {name = "SESSION", class_name = "WebMultiViewSession"}
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["WebMultiViewSync", "WebMultiViewSession"]